### ISSUE TITLE
Clear Button Bug

### ISSUE THREAD

**Issue by C0d3K1ng** [C0d3K1ng/Ecolog#5]
On the Calculator page, upon hitting the clear button after all the fields have been filled or left blank the clear button just randomly closes (crash?) the program with no explanation why. It's really embarrassing for a senior project and if you don't want to be the laughing stock of the school you better fix it.
There are few possible avenues:

- [ ] Find the line/s of code and correct it.
- [ ] Use the Debugger to see where the issue arises
- [ ] Delete the class that causes it
- [ ] Roll back the project to a working version
- [ ] Make the Calculator and Math Class one
- [ ] Delete the entire project and start over

**Comment by aseemsahoo** [comment]
You can assign this issue to me.

**Comment by aseemsahoo** [comment]
I have given a PR addressing this issue. Do check.
Thanks.
